### ISSUE TITLE
How to properly handle initialization timeouts and errors?

### ISSUE THREAD

**Issue by jefersondaniel** [statsig-io/node-js-server-sdk#24]
I was testing the `initTimeoutMs` option and noticed that the timeout behavior of the application is to enter an empty state and return false for every flags. However I would like to know when the FF failed so I do another behavior, like logging or returning an error.

What is the recommended practice here?

**Comment by kenny-statsig** [comment]
We don't support a callback specifically for initialize timeouts. But there is a `rulesUpdatedCallback` option which is triggered after successfully populating the store. If this callback is not triggered after `initTimeoutMs` elapsed, then I suppose you could treat it as a timeout.

**Comment by bgmort** [comment]
@kenny-statsig is there a reason there is no callback or other way to explicitly handle an initialization timeout? It would definitely be helpful for logging/troubleshooting purposes, and there would be less chance of developer errors or weird timing issues if the library provider the handler rather than us doing our own setTimeout check.
